config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'

  # For the robots
  get '/sitemap.xml', to: 'pages#sitemap', format: 'xml'

  resources :beers, only: [:index, :show] do
    member do
      get 'show_description'
    end
  end
  resources :posts, only: [:index, :show]

  devise_for :users, skip: [:registrations]

  namespace :api do
    resource :hourly_data_points, only: [:index, :create]
    resources :beers, only: [:index, :show] do
      resources :hourly_data_points, only: [:index]
    end
  end

  namespace :admin do
    root to: 'beers#index'
    resources :beers
    resources :beer_daily_data_points
    resources :beer_hourly_data_points

    resources :posts
    resources :users
    authenticate :user do
      mount GoodJob::Engine => 'good_job'
    end
  end

  post '/graphql', to: 'graphql#execute'
end

app/views/pages/home/_beers.html.erb
<div class="relative py-12 px-4 sm:px-6 lg:py-16 lg:px-8">
  <div class="relative max-w-7xl mx-auto">
    <%= render partial: 'beers/index/beers', locals: { beers: beers } %>
  </div>
</div>

app/views/pages/home/_content.html.erb
<div class="py-16 overflow-hidden lg:py-24">
  <div class="relative max-w-xl mx-auto px-4 sm:px-6 lg:px-8 lg:max-w-screen-xl">
    <div class="relative">
      <h3 class="text-center text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl sm:leading-10">
        More fun. More beer.
      </h3>
      <p class="mt-4 max-w-3xl mx-auto text-center text-xl leading-7 text-gray-500">
        We're some beer brewers based out of Fargo, ND. We don't brew commercially.
      </p>
    </div>

    <div class="relative mt-12 lg:mt-24 lg:grid lg:grid-cols-2 lg:gap-8 lg:items-center">
      <div class="relative">
        <h4 class="text-2xl leading-8 font-extrabold text-gray-900 tracking-tight sm:text-3xl sm:leading-9">
          Support locally made beer.
        </h4>
        <p class="mt-3 text-lg leading-7 text-gray-500">
          Consider supporting your local homebrewing association. They always accept new members, and often times have great recommentations!
          <a class="text-indigo-600" href="https://www.homebrewersassociation.org/">Find your local association</a>
        </p>

        <ul class="mt-10">
          <li>
            <div class="flex">
              <div class="flex-shrink-0">
                <div class="flex items-center justify-center h-12 w-12 rounded-md bg-indigo-500 text-white">
                  <i class="fad fa-globe-stand fa-2x"></i>
                </div>
              </div>
              <div class="ml-4">
                <h5 class="text-lg leading-6 font-medium text-gray-900">All over the globe</h5>
                <p class="mt-2 text-base leading-6 text-gray-500">
                  No matter where you are, you can try to find your local homebrewers association.
                </p>
              </div>
            </div>
          </li>
          <li class="mt-10">
            <div class="flex">
              <div class="flex-shrink-0">
                <div class="flex items-center justify-center h-12 w-12 rounded-md bg-indigo-500 text-white">
                  <i class="fad fa-boxing-glove fa-2x"></i>
                </div>
              </div>
              <div class="ml-4">
                <h5 class="text-lg leading-6 font-medium text-gray-900">Help out the little guy</h5>
                <p class="mt-2 text-base leading-6 text-gray-500">
                  Big companies make all the money. Small brewers have all the fun. Help out the "Davids" of the world.
                </p>
              </div>
            </div>
          </li>
          <li class="mt-10">
            <div class="flex">
              <div class="flex-shrink-0">
                <div class="flex items-center justify-center h-12 w-12 rounded-md bg-indigo-500 text-white">
                  <i class="fad fa-stopwatch fa-2x"></i>
                </div>
              </div>
              <div class="ml-4">
                <h5 class="text-lg leading-6 font-medium text-gray-900">Take the time to care</h5>
                <p class="mt-2 text-base leading-6 text-gray-500">
                  Brewing beer is a long process. Brewing beer locally can take anywhere from 3-4 weeks.
                </p>
              </div>
            </div>
          </li>
        </ul>
      </div>

      <div class="mt-10 -mx-4 relative lg:mt-0">
        <%= image_tag 'brewing-step-one.jpg', alt: 'Brewing it up.', class: 'relative mx-auto', width: '490' %>
      </div>
    </div>

    <div class="relative mt-12 sm:mt-16 lg:mt-24">
      <div class="lg:grid lg:grid-flow-row-dense lg:grid-cols-2 lg:gap-8 lg:items-center">
        <div class="lg:col-start-2">
          <h4 class="text-2xl leading-8 font-extrabold text-gray-900 tracking-tight sm:text-3xl sm:leading-9">
            Always in the loop
          </h4>
          <p class="mt-3 text-lg leading-7 text-gray-500">
            Check out out <%= link_to beers_path, 'our beers' %>, and check out the statistics we collect.
          </p>

          <ul class="mt-10">
            <li>
              <div class="flex">
                <div class="flex-shrink-0">
                  <div class="flex items-center justify-center h-12 w-12 rounded-md bg-indigo-500 text-white">
                    <i class="fad fa-mobile fa-2x"></i>
                  </div>
                </div>
                <div class="ml-4">
                  <h5 class="text-lg leading-6 font-medium text-gray-900">Mobile</h5>
                  <p class="mt-2 text-base leading-6 text-gray-500">
                    Follow the status of our brews from anywhere! We track the temperature and specific gravity as we brew.
                  </p>
                </div>
              </div>
            </li>
            <li class="mt-10">
              <div class="flex">
                <div class="flex-shrink-0">
                  <div class="flex items-center justify-center h-12 w-12 rounded-md bg-indigo-500 text-white">
                    <i class="fad fa-jug fa-2x"></i>
                  </div>
                </div>
                <div class="ml-4">
                  <h5 class="text-lg leading-6 font-medium text-gray-900">Status</h5>
                  <p class="mt-2 text-base leading-6 text-gray-500">
                    You'll know when we've finished, as our web app updates every day with the status.
                  </p>
                </div>
              </div>
            </li>
          </ul>
        </div>

        <div class="mt-10 -mx-4 relative lg:mt-0 lg:col-start-1">
          <%= image_tag 'brewing-step-two.jpg', alt: 'Finishing the brew', class: 'relative mx-auto', width: '490' %>
        </div>
      </div>
    </div>
  </div>
</div>