config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'

  # For the robots
  get '/sitemap.xml', to: 'pages#sitemap', format: 'xml'

  resources :beers, only: [:index, :show] do
    member do
      get 'show_description'
    end
  end
  resources :posts, only: [:index, :show]

  devise_for :users, skip: [:registrations]

  namespace :api do
    resource :hourly_data_points, only: [:index, :create]
    resources :beers, only: [:index, :show] do
      resources :hourly_data_points, only: [:index]
    end
  end

  namespace :admin do
    root to: 'beers#index'
    resources :beers
    resources :beer_daily_data_points
    resources :beer_hourly_data_points

    resources :posts
    resources :users
    authenticate :user do
      mount GoodJob::Engine => 'good_job'
    end
  end

  post '/graphql', to: 'graphql#execute'
end

app/models/beer.rb
# frozen_string_literal: true

# A beer that we are brewing
class Beer < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :carboys, dependent: :destroy
  has_many :beer_daily_data_points, dependent: :destroy
  has_many :beer_hourly_data_points, dependent: :destroy
  has_rich_text :recipe

  def most_recent_daily_data_point
    @most_recent_daily_data_point ||= beer_daily_data_points.last
  end

  def most_recent_daily_avg_temperature
    temp = most_recent_daily_data_point&.avg_temperature
    temp ? "#{temp.round(2)} °F" : 'N/A'
  end

  def most_recent_daily_avg_specific_gravity
    gravity = most_recent_daily_data_point&.avg_specific_gravity
    gravity ? gravity.round(3).to_s : 'N/A'
  end

  def earliest_daily_data_point
    @earliest_daily_data_point ||= beer_daily_data_points.first
  end

  def earliest_daily_avg_temperature
    temp = earliest_daily_data_point&.avg_temperature
    temp ? "#{temp.round(2)} °F" : 'N/A'
  end

  def earliest_daily_avg_specific_gravity
    gravity = earliest_daily_data_point&.avg_specific_gravity
    gravity ? gravity.round(3).to_s : 'N/A'
  end

  def current_alcohol_content
    return 0 unless beer_daily_data_points.size.positive?
    return 0 if most_recent_daily_data_point == earliest_daily_data_point

    gravity_diff = earliest_daily_data_point.avg_specific_gravity - most_recent_daily_data_point.avg_specific_gravity
    gravity_diff * 131.25
  end

  def started?
    return false unless start_date

    Time.zone.today > start_date
  end

  def bottled?
    return false unless bottle_date

    Time.zone.today > bottle_date
  end

  def brewed?
    return false unless ready_date

    Time.zone.today > ready_date
  end

  def time_after_start_before_bottle
    return 0 unless started?
    return bottle_date - start_date if bottled?

    Time.zone.today - start_date
  end

  def time_until_bottle
    return bottle_date - start_date unless started?
    return 0 if bottled?

    bottle_date - Time.zone.today
  end

  def time_after_bottle_before_ready
    return 0 unless bottled?
    return bottle_date - start_date if !bottled? || brewed?

    Time.zone.today - bottle_date
  end

  def time_until_ready
    return ready_date - bottle_date unless bottled?
    return 0 if brewed?

    ready_date - Time.zone.today
  end
end

app/controllers/admin/beers_controller.rb
# frozen_string_literal: true

module Admin
  # Overview of Beer
  class BeersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    def find_resource(param)
      Beer.friendly.find(param)
    end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information

    def default_sorting_attribute
      :start_date
    end

    def default_sorting_direction
      :desc
    end
  end
end

app/controllers/api/beers_controller.rb
# frozen_string_literal: true

module Api
  # Handles any beer posts
  class BeersController < ApiController
    before_action :set_beers

    def index
      paginate json: @beers
    end

    def show
      beer = @beers.find(params[:id])
      render json: beer
    end

    private

    def set_beers
      @beers = Beer.all
    end
  end
end

app/controllers/beers_controller.rb
# frozen_string_literal: true

# Beers that we are brewing
class BeersController < ApplicationController
  before_action :set_beers

  def index
    @beers = @beers.page(params[:page]).per(12)
    @title = 'Beers at Rotator IPA'
  end

  def show
    @beer = Beer.friendly.find(params[:id])
    @beers = @beers.where.not(id: @beer.id).order(start_date: :desc).first(3)
    @title = @beer.name
  end

  def show_description
    @hide_header = true
    @beer = Beer.friendly.find(params[:id])
  end

  private

  def set_beers
    @beers = Beer.all.order(start_date: :desc)
  end
end

app/views/beers/_beer.html.erb
<div class="flex flex-col rounded-lg shadow-lg overflow-hidden">
  <div class="flex-shrink-0">
    <div class="relative h-48 w-full flex justify-center items-center">
      <%= render partial: 'beers/beer_chart', locals: { beer: beer } %>
    </div>
  </div>
  <div class="flex-1 bg-white p-6 flex flex-col justify-between z-10">
    <div class="flex-1">
      <p class="text-sm leading-5 font-medium text-indigo-600">
        <a href="<%= beer_url(beer) %>" class="hover:underline">
          <%= beer.kind %>
        </a>
      </p>
      <a href="<%= beer_url(beer) %>" class="block">
        <h3 class="mt-2 text-xl leading-7 font-semibold text-gray-900">
          <%= beer.name %>
        </h3>
        <p class="mt-3 text-base leading-6 text-gray-500">
          <%= beer.description %>
        </p>
      </a>
    </div>
  </div>
</div>

app/views/beers/_beer_chart.html.erb
<canvas id="beer-<%= beer.id %>" class="my-auto"></canvas>
<script type="text/javascript">
  var ctx = document.getElementById('beer-<%= beer.id %>').getContext('2d');
  var data = {
    datasets: [{
      data: [
        <%= beer.time_after_start_before_bottle.to_i %>,
        <%= beer.time_until_bottle.to_i %>,
        <%= beer.time_after_bottle_before_ready.to_i %>,
        <%= beer.time_until_ready.to_i %>,
      ],
      backgroundColor: [
        'forestgreen',
        'gainsboro',
        'forestgreen',
        'gainsboro'
      ]
    }],
    // These labels appear in the legend and in the tooltips when hovering different arcs
    labels: [
      '<%= beer.bottled? ? "Beer is bottled" : "Days elapsed since start" %>',
      'Days until bottled',
      '<%= beer.brewed? ? "Beer is brewed" : "Days elapsed since bottled" %>',
      'Days until brewed',
    ]
  };
  var options = {
    rotation: -Math.PI,
    circumference: Math.PI,
    legend: {
      display: false,
    },
    aspectRatio: 2.30,
  };
  new Chart(ctx, {
    type: 'doughnut',
    data: data,
    options: options
  });
</script>

app/views/beers/_beers.html.erb
<div class="mt-12 grid gap-5 max-w-lg mx-auto lg:grid-cols-3 lg:max-w-none">
  <% beers.each do |beer|  %>
    <% cache beer, expires_in: 8.hours do %>
      <%= render partial: 'beers/beer', locals: { beer: beer } %>
    <% end %>
  <% end %>
</div>

app/views/beers/_header.html.erb
<% unless @hide_header %>
<div class="relative bg-white" data-controller="dropdown">
  <div class="max-w-screen-xl mx-auto">
    <div class="relative z-10 pb-20 bg-white lg:max-w-2xl lg:w-full">
      <div class="relative pt-6 px-4 sm:px-6 lg:px-8">
        <nav class="relative flex items-center justify-between sm:h-10 lg:justify-start">
          <div class="flex items-center flex-grow flex-shrink-0 lg:flex-grow-0">
            <div class="flex items-center justify-between w-full md:w-auto">
              <a href="/" aria-label="Home">
                <%= image_tag 'ipa-logo.png', alt: 'Rotator IPA', class: 'h-8 w-auto sm:h-10' %>
              </a>
              <div class="-mr-2 flex items-center md:hidden">
                <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out" id="main-menu" aria-label="Main menu" aria-haspopup="true" data-action="click->dropdown#toggle click@window->dropdown#hide">
                  <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                  </svg>
                </button>
              </div>
            </div>
          </div>
          <div class="hidden md:block md:ml-10 md:pr-4">
            <a href="/beers" class="font-medium text-gray-500 hover:text-gray-900 transition duration-150 ease-in-out">Beers</a>
          </div>
          <div class="hidden md:block md:ml-10 md:pr-4">
            <a href="/posts" class="font-medium text-gray-500 hover:text-gray-900 transition duration-150 ease-in-out">Blog</a>
          </div>
        </nav>
      </div>
      <div
        class="absolute top-0 inset-x-0 p-2 transition transform origin-top-right hidden md:hidden z-10"
        data-dropdown-target="menu"
        data-dropdown-invisible-class="opacity-0 scale-95"
        data-dropdown-visible-class="opacity-100 scale-100"
        data-dropdown-entering-class="ease-out duration-300"
        data-dropdown-enter-timeout="300"
        data-dropdown-leaving-class="ease-in duration-300"
        data-dropdown-leave-timeout="300"
      >
        <div class="rounded-lg shadow-md">
          <div class="rounded-lg bg-white shadow-xs overflow-hidden" role="menu" aria-orientation="vertical" aria-labelledby="main-menu">
            <div class="px-5 pt-4 flex items-center justify-between">
              <a href="/">
                <%= image_tag 'ipa-logo.png', alt: 'Rotator IPA', class: 'h-8 w-auto' %>
              </a>
              <div class="-mr-2">
                <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out" aria-label="Close menu" data-action="click->dropdown#toggle click@window->dropdown#hide">
                  <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            </div>
            <div class="px-2 pt-2 pb-3">
              <a href="/beers" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-gray-900 hover:bg-gray-50 focus:outline-none focus:text-gray-900 focus:bg-gray-50 transition duration-150 ease-in-out" role="menuitem">Beers</a>
            </div>
            <div class="px-2 pb-3">
              <a href="/posts" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-gray-900 hover:bg-gray-50 focus:outline-none focus:text-gray-900 focus:bg-gray-50 transition duration-150 ease-in-out" role="menuitem">Blog</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/beers/index.html.erb
<% content_for :head do %>
  <meta property="og:title" content="Beers at Rotator IPA">
  <meta property="og:description" content="No. They aren't all ready to drink yet.">
  <meta property="og:image" content="https://rotatoripa.co/rotator-ipa-sharing-icon.png">
  <meta property="og:url" content="https://rotatoripa.co/beers">
  <meta name="twitter:title" content="Beers at Rotator IPA">
  <meta name="twitter:description" content="No. They aren't all ready to drink yet.">
  <meta name="twitter:image" content="https://rotatoripa.co/rotator-ipa-sharing-icon.png">
  <meta name="twitter:card" content="summary_large_image">
  <link itemprop="thumbnailUrl" href="https://rotatoripa.co/rotator-ipa-sharing-icon.png">
<% end %>

<%= render partial: 'beers/header' %>

<div class="relative pb-20 px-4 sm:px-6 lg:pb-28 lg:px-8">
  <div class="absolute inset-0">
    <div class="bg-white h-1/3 sm:h-2/3"></div>
  </div>
  <div class="relative max-w-7xl mx-auto">
    <div class="text-center">
      <h2 class="text-3xl leading-9 tracking-tight font-extrabold text-gray-900 sm:text-4xl sm:leading-10">
        Beers we're brewing
      </h2>
      <p class="mt-3 max-w-2xl mx-auto text-xl leading-7 text-gray-500 sm:mt-4">
        We cycle out beers every two weeks, so be sure to check back!
      </p>
    </div>
    <%= render partial: 'beers/index/beers', locals: { beers: @beers } %>
  </div>
</div>


<div class="flex justify-center">
  <% unless @beers.first_page? %>
    <%= link_to_previous_page @beers, 'Previous Page' %>
  <% end %>
  <% if @beers.current_page < @beers.total_pages && @beers.current_page > 1 %>
    <span class="mx-2">|</span>
  <% end %>
  <% unless @beers.last_page? %>
    <%= link_to_next_page @beers, 'Next Page' %>
  <% end %>
</div>

<div class="flex justify-center mt-4">
  <span>
    <%= page_entries_info @beers %>
  </span>
</div>



<%= render partial: 'pages/footer' %>

app/views/beers/show.html.erb
<% content_for :head do %>
  <meta property="og:title" content="<%= @beer.name %>">
  <meta property="og:description" content="<%= @beer.description %>">
  <meta property="og:image" content="https://rotatoripa.co/rotator-ipa-sharing-icon.png">
  <meta property="og:url" content="<%= beer_url(@beer) %>">
  <meta name="twitter:title" content="<%= @beer.name %>">
  <meta name="twitter:description" content="<%= @beer.description %>">
  <meta name="twitter:image" content="https://rotatoripa.co/rotator-ipa-sharing-icon.png">
  <meta name="twitter:card" content="summary_large_image">
  <link itemprop="thumbnailUrl" href="https://rotatoripa.co/rotator-ipa-sharing-icon.png">
<% end %>

<%= render partial: 'beers/header' %>

<% cache @beer, expires_in: 8.hours do %>
<div class="relative pb-16 bg-white overflow-hidden">
  <div class="relative px-4 sm:px-6 lg:px-8">
    <div class="text-lg max-w-prose mx-auto mb-6">
      <h1 class="mt-2 mb-8 text-3xl text-center leading-normal font-extrabold tracking-tight text-gray-900 sm:text-6xl sm:leading-tight"><%= @beer.name %></h1>
    </div>
    <%= render partial: 'beers/show/stats', locals: { beer: @beer } %>
    <% if @beer.most_recent_daily_data_point %>
      <%= render partial: 'beers/show/alcohol', locals: { beer: @beer } %>
    <% end %>
    <div class="max-w-prose mx-auto mb-32">
      <%= render partial: 'beers/shared/beer_chart', locals: { beer: @beer } %>
    </div>
    <div class="mx-auto mb-32 flex flex-row flex-wrap justify-center">
      <% if @beer.carboys.size.positive? %>
        <% @beer.carboys.each.with_index do |carboy, index| %>
          <div class="px-0 md:px-8 mt-16 md:mt-0 w-full md:w-6/12">
            <h4 class="text-center leading-5 font-medium text-gray-500 mb-4">Carboy #<%= index + 1 %></h4>
            <div data-controller="hourly-chart" data-hourly-chart-beer-value="<%= @beer.friendly_id %>" data-hourly-chart-carboy-value="<%= carboy.id %>">
            <div class="text-center mt-16 flex justify-center" role="status" data-hourly-chart-target="loading">
              <svg aria-hidden="true" class="w-8 h-8 mr-2 text-gray-200 animate-spin dark:text-gray-600 fill-blue-600" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
                <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
              </svg>
              <span class="sr-only">Loading...</span>
            </div>
              <canvas data-hourly-chart-target="canvas" class="my-auto"></canvas>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="prose prose-lg text-gray-500 mx-auto">
      <%= @beer.recipe %>
    </div>
  </div>
</div>
<% end %>

<div class="relative max-w-7xl mx-auto">
  <%= render partial: 'beers/index/beers', locals: { beers: @beers } %>
</div>

<%= render partial: 'pages/footer' %>

app/views/beers/show_description.html.erb
<% content_for :head do %>
  <link rel="canonical" href="<%= beer_url(@beer) %>">
<% end %>

<%= render partial: 'beers/header' %>

<% cache @beer, expires_in: 8.hours do %>
<div class="prose prose-lg text-gray-500 mx-auto">
  <%= @beer.recipe %>
</div>
<% end %>