config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'

  # For the robots
  get '/sitemap.xml', to: 'pages#sitemap', format: 'xml'

  resources :beers, only: [:index, :show] do
    member do
      get 'show_description'
    end
  end
  resources :posts, only: [:index, :show]

  devise_for :users, skip: [:registrations]

  namespace :api do
    resource :hourly_data_points, only: [:index, :create]
    resources :beers, only: [:index, :show] do
      resources :hourly_data_points, only: [:index]
    end
  end

  namespace :admin do
    root to: 'beers#index'
    resources :beers
    resources :beer_daily_data_points
    resources :beer_hourly_data_points

    resources :posts
    resources :users
    authenticate :user do
      mount GoodJob::Engine => 'good_job'
    end
  end

  post '/graphql', to: 'graphql#execute'
end

app/models/post.rb
# frozen_string_literal: true

# Blog posts
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user

  has_rich_text :content

  def reading_time
    words_per_minute = 150
    text = Nokogiri::HTML(content.body.to_html).inner_text
    minutes = (text.scan(/\w+/).length / words_per_minute).to_i
    minutes.positive? ? minutes : 1
  end
end

app/controllers/admin/posts_controller.rb
# frozen_string_literal: true

module Admin
  # Overview of Blog Posts
  class PostsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    def find_resource(param)
      Post.friendly.find(param)
    end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# All the blog posts
class PostsController < ApplicationController
  before_action :set_posts

  def index
    @posts = @posts.page(params[:page]).per(12)
    @title = 'Rotator IPA Blog'
  end

  def show
    @post = @posts.friendly.find(params[:id])
    @posts = @posts.where.not(id: @post.id).first(3)
    @title = @post.title
  end

  private

  def set_posts
    @posts = if current_user
               Post.all.order(published_at: :desc)
             else
               Post.where(published: true).order(published_at: :desc)
             end
  end
end

app/views/posts/_header.html.erb
<div class="relative bg-white" data-controller="dropdown">
  <div class="max-w-screen-xl mx-auto">
    <div class="relative z-10 pb-20 bg-white lg:max-w-2xl lg:w-full">
      <div class="relative pt-6 px-4 sm:px-6 lg:px-8">
        <nav class="relative flex items-center justify-between sm:h-10 lg:justify-start">
          <div class="flex items-center flex-grow flex-shrink-0 lg:flex-grow-0">
            <div class="flex items-center justify-between w-full md:w-auto">
              <a href="/" aria-label="Home">
                <%= image_tag 'ipa-logo.png', alt: 'Rotator IPA', class: 'h-8 w-auto sm:h-10' %>
              </a>
              <div class="-mr-2 flex items-center md:hidden">
                <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out" id="main-menu" aria-label="Main menu" aria-haspopup="true" data-action="click->dropdown#toggle click@window->dropdown#hide">
                  <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                  </svg>
                </button>
              </div>
            </div>
          </div>
          <div class="hidden md:block md:ml-10 md:pr-4">
            <a href="/beers" class="font-medium text-gray-500 hover:text-gray-900 transition duration-150 ease-in-out">Beers</a>
          </div>
          <div class="hidden md:block md:ml-10 md:pr-4">
            <a href="/posts" class="font-medium text-gray-500 hover:text-gray-900 transition duration-150 ease-in-out">Blog</a>
          </div>
        </nav>
      </div>
      <div
        class="absolute top-0 inset-x-0 p-2 transition transform origin-top-right hidden md:hidden z-10"
        data-dropdown-target="menu"
        data-dropdown-invisible-class="opacity-0 scale-95"
        data-dropdown-visible-class="opacity-100 scale-100"
        data-dropdown-entering-class="ease-out duration-300"
        data-dropdown-enter-timeout="300"
        data-dropdown-leaving-class="ease-in duration-300"
        data-dropdown-leave-timeout="300"
      >
        <div class="rounded-lg shadow-md">
          <div class="rounded-lg bg-white shadow-xs overflow-hidden" role="menu" aria-orientation="vertical" aria-labelledby="main-menu">
            <div class="px-5 pt-4 flex items-center justify-between">
              <a href="/">
                <%= image_tag 'ipa-logo.png', alt: 'Rotator IPA', class: 'h-8 w-auto' %>
              </a>
              <div class="-mr-2">
                <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out" aria-label="Close menu" data-action="click->dropdown#toggle click@window->dropdown#hide">
                  <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            </div>
            <div class="px-2 pt-2 pb-3">
              <a href="/beers" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-gray-900 hover:bg-gray-50 focus:outline-none focus:text-gray-900 focus:bg-gray-50 transition duration-150 ease-in-out" role="menuitem">Beers</a>
            </div>
            <div class="px-2 pt-2 pb-3">
              <a href="/posts" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-gray-900 hover:bg-gray-50 focus:outline-none focus:text-gray-900 focus:bg-gray-50 transition duration-150 ease-in-out" role="menuitem">Blog</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% content_for :head do %>
  <meta property="og:title" content="Rotator IPA Blog">
  <meta property="og:description" content="Notes on brewing the beer you probably might want.">
  <meta property="og:image" content="https://rotatoripa.co/rotator-ipa-sharing-icon.png">
  <meta property="og:url" content="https://rotatoripa.co/posts">
  <meta name="twitter:title" content="Rotator IPA">
  <meta name="twitter:description" content="Notes on brewing the beer you probably might want.">
  <meta name="twitter:image" content="https://rotatoripa.co/rotator-ipa-sharing-icon.png">
  <meta name="twitter:card" content="summary_large_image">
  <link itemprop="thumbnailUrl" href="https://rotatoripa.co/rotator-ipa-sharing-icon.png">
<% end %>

<%= render partial: 'posts/header' %>

<div class="relative bg-gray-50 pb-20 px-4 sm:px-6 lg:pb-28 lg:px-8">
  <div class="absolute inset-0">
    <div class="bg-white h-1/3 sm:h-2/3"></div>
  </div>
  <div class="relative max-w-7xl mx-auto">
    <div class="text-center">
      <h2 class="text-3xl leading-9 tracking-tight font-extrabold text-gray-900 sm:text-4xl sm:leading-10">
        Hits from the blog
      </h2>
      <p class="mt-3 max-w-2xl mx-auto text-xl leading-7 text-gray-500 sm:mt-4">
        Some tidbits we've been working on. We've had some interesting experiences brewing beer.
      </p>
    </div>
    <%= render partial: 'posts/index/posts', locals: { posts: @posts } %>
  </div>
</div>

<div class="flex justify-center">
  <% unless @posts.first_page? %>
    <%= link_to_previous_page @posts, 'Previous Page' %>
  <% end %>
  <% if @posts.current_page < @posts.total_pages && @posts.current_page > 1 %>
    <span class="mx-2">|</span>
  <% end %>
  <% unless @posts.last_page? %>
    <%= link_to_next_page @posts, 'Next Page' %>
  <% end %>
</div>

<div class="flex justify-center mt-4">
  <span>
    <%= page_entries_info @posts %>
  </span>
</div>

<%= render partial: 'pages/footer' %>

app/views/posts/show.html.erb
<% content_for :head do %>
  <meta property="og:title" content="<%= @post.page_title || @post.title %>">
  <meta property="og:description" content="<%= @post.page_description || @post.description %>">
  <meta property="og:image" content="<%= @post.unsplash_image_url || 'https://rotatoripa.co/rotator-ipa-sharing-icon.png' %>">
  <meta property="og:url" content="<%= post_url(@post) %>">
  <meta name="twitter:title" content="<%= @post.page_title || @post.title %>">
  <meta name="twitter:description" content="<%= @post.page_description || @post.description %>">
  <meta name="twitter:image" content="<%= @post.unsplash_image_url || 'https://rotatoripa.co/rotator-ipa-sharing-icon.png' %>">
  <meta name="twitter:card" content="summary_large_image">
  <link itemprop="thumbnailUrl" href="<%= @post.unsplash_image_url || 'https://rotatoripa.co/rotator-ipa-sharing-icon.png' %>">

<% end %>

<%= render partial: 'posts/header' %>

<div class="relative pb-16 bg-white overflow-hidden">
  <div class="relative px-4 sm:px-6 lg:px-8">
    <div class="text-lg max-w-prose mx-auto mb-6">
      <h1 class="mt-2 mb-8 text-3xl text-center leading-normal font-extrabold tracking-tight text-gray-900 sm:text-6xl sm:leading-none"><%= @post.title %></h1>
      <p class="text-xl text-gray-500 leading-8"><%= @post.description %></p>
    </div>
    <div class="prose prose-lg text-gray-500 mx-auto">
      <%= @post.content %>
    </div>
  </div>
</div>

<%= render partial: 'posts/show/posts', locals: { posts: @posts } %>

<%= render partial: 'pages/footer' %>